language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - composer selfupdate

install:
  - composer install

script:
  - if [[ "$TRAVIS_BRANCH" == "master" && $TRAVIS_PULL_REQUEST == false ]];
    then bin/phpunit -c phpunit.xml;
    else bin/phpunit -c phpunit.xml --testsuite unit;
    fi
